# Generated by Django 4.2.15 on 2024-09-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catInfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='主名')),
                ('sex', models.SmallIntegerField(verbose_name='性别')),
                ('kind', models.SmallIntegerField(verbose_name='花色')),
            ],
        ),
    ]
