# Generated by Django 4.2.15 on 2024-09-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catinfor',
            name='kind',
            field=models.CharField(max_length=10, verbose_name='花色'),
        ),
        migrations.AlterField(
            model_name='catinfor',
            name='sex',
            field=models.CharField(max_length=10, verbose_name='性别'),
        ),
    ]
