# Generated by Django 4.2.15 on 2024-09-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_alter_catinfor_kind_alter_catinfor_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='catinfor',
            name='breed',
            field=models.CharField(default='unknown', max_length=10, verbose_name='花色_en'),
        ),
    ]
