# Generated by Django 4.2.15 on 2024-09-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_catinfor_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='catinfor',
            name='description',
            field=models.CharField(default='', max_length=100, verbose_name='基本介绍'),
        ),
    ]
