# Generated by Django 4.2.15 on 2024-09-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_catinfor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='catinfor',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=30.533741, max_digits=9, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='catinfor',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=114.361543, max_digits=9, verbose_name='经度'),
        ),
    ]
