# Generated by Django 4.2.15 on 2024-09-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_catinfor_latitude_catinfor_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='catinfor',
            name='activity_radius',
            field=models.IntegerField(default=100, verbose_name='活动半径（米）'),
        ),
    ]
