# Generated by Django 4.2.15 on 2024-09-15 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_catinfor_activity_radius_catinfor_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catinfor',
            name='activity_radius',
        ),
        migrations.RemoveField(
            model_name='catinfor',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='catinfor',
            name='longitude',
        ),
    ]
