# Generated by Django 4.2.15 on 2024-09-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_remove_catinfor_activity_radius_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catinfor',
            name='activity_radius',
            field=models.IntegerField(default=100, verbose_name='活动半径（米）'),
        ),
        migrations.AddField(
            model_name='catinfor',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=30.533741, max_digits=9, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='catinfor',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=114.361543, max_digits=9, verbose_name='经度'),
        ),
    ]
