# Generated by Django 4.2.15 on 2024-09-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_catinfor_activity_radius_catinfor_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catinfor',
            name='kind',
        ),
        migrations.AddField(
            model_name='catinfor',
            name='breed_en',
            field=models.CharField(default='unknown', max_length=10, verbose_name='花色_en'),
        ),
        migrations.AlterField(
            model_name='catinfor',
            name='breed',
            field=models.CharField(max_length=10, verbose_name='花色'),
        ),
    ]
