# Generated by Django 4.2.15 on 2024-09-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0011_remove_catinfor_kind_catinfor_breed_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.IntegerField(verbose_name='猫的id')),
                ('content', models.CharField(max_length=100, verbose_name='通知内容')),
                ('human', models.CharField(max_length=10, verbose_name='通知者')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='通知时间')),
            ],
        ),
    ]
